// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CM
double CM(NumericVector tab);
RcppExport SEXP cauchyTest_CM(SEXP tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tab(tabSEXP);
    __result = Rcpp::wrap(CM(tab));
    return __result;
END_RCPP
}
// AD
double AD(NumericVector tab);
RcppExport SEXP cauchyTest_AD(SEXP tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tab(tabSEXP);
    __result = Rcpp::wrap(AD(tab));
    return __result;
END_RCPP
}
// Watson
double Watson(NumericVector tab);
RcppExport SEXP cauchyTest_Watson(SEXP tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tab(tabSEXP);
    __result = Rcpp::wrap(Watson(tab));
    return __result;
END_RCPP
}
// ModCM
double ModCM(NumericVector tab);
RcppExport SEXP cauchyTest_ModCM(SEXP tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tab(tabSEXP);
    __result = Rcpp::wrap(ModCM(tab));
    return __result;
END_RCPP
}
// Kuiper
double Kuiper(NumericVector tab);
RcppExport SEXP cauchyTest_Kuiper(SEXP tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tab(tabSEXP);
    __result = Rcpp::wrap(Kuiper(tab));
    return __result;
END_RCPP
}
// ECF
double ECF(NumericVector tab);
RcppExport SEXP cauchyTest_ECF(SEXP tabSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tab(tabSEXP);
    __result = Rcpp::wrap(ECF(tab));
    return __result;
END_RCPP
}
