# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  Test Cramera-von Misesa
#'
#' @param tab niepusty, bez braków danych wektor z danymi.
#' @export
CM <- function(tab) {
    .Call('cauchyTest_CM', PACKAGE = 'cauchyTest', tab)
}

#'  Test Andersona-Darlinga
#'
#' @param tab niepusty, bez braków danych wektor z danymi.
#' @export
AD <- function(tab) {
    .Call('cauchyTest_AD', PACKAGE = 'cauchyTest', tab)
}

#'  Test Watsona
#'
#' @param tab niepusty, bez braków danych wektor z danymi.
#' @export
Watson <- function(tab) {
    .Call('cauchyTest_Watson', PACKAGE = 'cauchyTest', tab)
}

#' Modyfikacja testu Cramera-von Misesa
#'
#' @param tab niepusty, bez braków danych wektor z danymi.
#' @export
ModCM <- function(tab) {
    .Call('cauchyTest_ModCM', PACKAGE = 'cauchyTest', tab)
}

#'  Test Kuipera
#'
#' @param tab niepusty, bez braków danych wektor z danymi.
#' @export
Kuiper <- function(tab) {
    .Call('cauchyTest_Kuiper', PACKAGE = 'cauchyTest', tab)
}

#' Test ECF
#'
#' @param tab niepusty, bez braków danych wektor z danymi.
#' @export
ECF <- function(tab) {
    .Call('cauchyTest_ECF', PACKAGE = 'cauchyTest', tab)
}

